name: Continuous Integration for Terraform modules
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Modules/**'


jobs:
  ci-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: bertei/berna-reusable-workflows/.github/workflows/ci-tf-modules.yaml@main
        with:
          tf_fmt: true
          add_tf_fmt: true
          render_readme: true